spring.application.name=app
mapbox.access-token=${MAPBOX_ACCESS_TOKEN}
# disable auto-commit: these both settings go hand in hand
spring.datasource.hikari.autoCommit=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8
#&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.connectionTimeout=50000
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=900000
spring.datasource.hikari.maximumPoolSize=8
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.poolName=MyPool
spring.datasource.hikari.connectionTestQuery=select 1 from dual
#spring.flyway.enabled=true
#
## Location where Flyway looks for migration scripts.
## By convention: src/main/resources/db/migration
#spring.flyway.locations=classpath:db/migration